USE [RWA]
GO
/****** Object:  Table [dbo].[HELIOS_PARAM_PERIMETRE_DETTE]    Script Date: 01/26/2024 4:45:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HELIOS_PARAM_PERIMETRE_DETTE](
	[CodeProduit] [nvarchar](5) NOT NULL,
	[LibelleProduit] [nvarchar](80) NULL,
	[LastUpdate] [nvarchar](40) NOT NULL,
 CONSTRAINT [PK_HELIOS_PARAM_PERIMETRE_DETTE] PRIMARY KEY CLUSTERED 
(
	[CodeProduit] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_HELIOS_PARAM_PERIMETRE_DETTE] ON dbo.[HELIOS_PARAM_PERIMETRE_DETTE] ([CodeProduit] ASC);
GO